import { describe, expect, it } from 'vitest';
import { BaselineError } from '../../src/baseline/errors';
import type { HeaderMeta } from '../../src/baseline/types';
import { generateMigration } from '../../src/codegen';
import { renderMigration } from '../../src/codegen/render';
import type { GenerateOptions } from '../../src/codegen/types';
import type { Column, ModelObject } from '../../src/introspect/types';
import {
  defaultSequenceOptions,
  dependsOn,
  makeColumn,
  makeComposite,
  makeConstraint,
  makeDomain,
  makeFunction,
  makeMaterializedView,
  makeSequence,
  makeTable,
  makeView,
  modelOf,
} from '../introspect/objects';
import { loadMigration, runUp } from './run';
import { canonicalStatements, canonicalSteps } from './sql';

const OPTIONS: GenerateOptions = {
  language: 'ts',
  defaultSchema: 'public',
  migrationName: '1700000000000_baseline',
  fakeCommand: 'node-pg-migrate up 1700000000000_baseline --fake',
  source: { serverVersion: '18.6' },
};

const HEADER: HeaderMeta = {
  migrationName: '1700000000000_baseline',
  fakeCommand: OPTIONS.fakeCommand,
  source: { serverVersion: '18.6' },
  materializedViews: 0,
  relations: 1,
};

/**
 * The text of the header comment of a migration (its first `//` lines), as
 * one line: a note may be wrapped over several lines.
 */
function headerText(content: string): string {
  const lines = content.split('\n');
  const end = lines.findIndex((line) => !line.startsWith('//'));

  return lines
    .slice(0, end === -1 ? lines.length : end)
    .map((line) => line.slice(2).trim())
    .join(' ');
}

function thrownBy(action: () => unknown): unknown {
  try {
    action();
  } catch (error) {
    return error;
  }

  return undefined;
}

function serialColumn(table: string): Column {
  return makeColumn('id', 'integer', {
    notNull: true,
    default: `nextval('public.${table}_id_seq'::regclass)`,
    ownedSequence: {
      name: { schema: 'public', name: `${table}_id_seq` },
      options: defaultSequenceOptions('integer'),
      unlogged: false,
    },
  });
}

describe('renderMigration', () => {
  it.each<[string, HeaderMeta['source'], string]>([
    [
      'a server and pg_dump',
      { serverVersion: '18.6', pgDumpVersion: '18.1' },
      'from PostgreSQL 18.6 (pg_dump 18.1).',
    ],
    ['an unknown server', {}, 'from PostgreSQL.'],
    [
      'a file',
      { file: 'schema.sql', serverVersion: '16.4', pgDumpVersion: '16.4' },
      'from schema.sql (PostgreSQL 16.4, pg_dump 16.4).',
    ],
    ['a file without versions', { file: 'stdin' }, 'from stdin.'],
  ])('says where the schema comes from for %s', (_, source, expected) => {
    const content = renderMigration([], {
      language: 'js',
      header: { ...HEADER, source },
    });

    expect(content.split('\n')[0]).toBe(
      `// Baseline generated by \`node-pg-migrate baseline --format js\` ${expected}`
    );
  });

  it('says that materialized views are created WITH NO DATA, to refresh after the first run', () => {
    const content = renderMigration([], {
      language: 'ts',
      header: { ...HEADER, materializedViews: 1 },
    });
    const header = headerText(content);

    expect(header).toContain('WITH NO DATA');
    expect(header).toMatch(/\brefresh\b.*\bafter the first run\b/i);
    expect(header).not.toContain('WITH DATA');
  });

  it('keeps every line of the header a comment when the command has line breaks', () => {
    const content = renderMigration([], {
      language: 'ts',
      header: {
        ...HEADER,
        fakeCommand: "node-pg-migrate up x --fake -m 'a\nb c'",
      },
    });

    expect(content).toContain("//   node-pg-migrate up x --fake -m 'a b c'");
  });
});

describe('generateMigration', () => {
  it('creates what uses a serial sequence after the table that creates it', async () => {
    const orders = makeTable('public', 'orders', {
      columns: [serialColumn('orders')],
    });
    const sequence = makeSequence('public', 'orders_id_seq', {
      ...defaultSequenceOptions('integer'),
      ownedBy: { table: { schema: 'public', name: 'orders' }, column: 'id' },
      comment: 'Order numbers',
    });
    const archive = makeTable('public', 'archive', {
      columns: [
        makeColumn('id', 'integer', {
          default: "nextval('public.orders_id_seq'::regclass)",
        }),
      ],
    });
    const model = modelOf(
      [orders, sequence, archive],
      [dependsOn(orders, sequence), dependsOn(archive, sequence)]
    );

    const sql = canonicalSteps(
      await runUp(
        await loadMigration(generateMigration(model, OPTIONS).content, 'ts')
      )
    );

    expect(sql.slice(2, -1)).toStrictEqual([
      'create table orders ( id serial )',
      "create table archive ( id integer default nextval ( 'public.orders_id_seq' :: regclass ) )",
      "comment on sequence public . orders_id_seq is 'Order numbers'",
    ]);
  });

  it('creates a sequence that no serial column made on its own, and sets its owner after the table', async () => {
    const sequence = makeSequence('public', 'ticket_numbers', {
      ownedBy: { table: { schema: 'public', name: 'tickets' }, column: 'no' },
    });
    const tickets = makeTable('public', 'tickets', {
      columns: [
        makeColumn('no', 'bigint', {
          notNull: true,
          default: "nextval('public.ticket_numbers'::regclass)",
          ownedSequence: {
            name: { schema: 'public', name: 'ticket_numbers' },
            options: defaultSequenceOptions('bigint'),
            unlogged: false,
          },
        }),
      ],
    });

    const sql = canonicalSteps(
      await runUp(
        await loadMigration(
          generateMigration(
            modelOf([tickets, sequence], [dependsOn(tickets, sequence)]),
            OPTIONS
          ).content,
          'ts'
        )
      )
    );

    expect(sql.slice(2, -1)).toStrictEqual(
      canonicalStatements(
        `CREATE SEQUENCE ticket_numbers;
         CREATE TABLE tickets (no bigint DEFAULT nextval('public.ticket_numbers'::regclass) NOT NULL);
         ALTER SEQUENCE ticket_numbers OWNED BY public.tickets.no;`
      )
    );
  });

  it('creates a serial sequence on its own when a function that a default of its table calls uses it, instead of refusing a cycle', async () => {
    const sequence = makeSequence('public', 'a_id_seq', {
      ...defaultSequenceOptions('integer'),
      ownedBy: { table: { schema: 'public', name: 'a' }, column: 'id' },
    });
    const nextCode = makeFunction('public', 'next_code', {
      returns: 'text',
      hasSqlBody: true,
      definition:
        "CREATE OR REPLACE FUNCTION public.next_code()\n RETURNS text\n LANGUAGE sql\nBEGIN ATOMIC\n SELECT ('C-'::text || nextval('public.a_id_seq'::regclass));\nEND\n",
    });
    const table = makeTable('public', 'a', {
      columns: [
        serialColumn('a'),
        makeColumn('v', 'text'),
        makeColumn('code', 'text', { default: 'public.next_code()' }),
      ],
    });
    // What pg_depend records: the defaults of the table use the sequence and
    // the function, and the SQL-standard body of the function uses the
    // sequence.
    const model = modelOf(
      [sequence, nextCode, table],
      [
        dependsOn(table, sequence),
        dependsOn(table, nextCode),
        dependsOn(nextCode, sequence),
      ]
    );

    // Writing the column as serial makes the sequence wait for its table, and
    // so for the function: a cycle, which the schema itself does not have.
    expect(thrownBy(() => generateMigration(model, OPTIONS))).toBeUndefined();

    const { content } = generateMigration(model, OPTIONS);
    const sql = canonicalSteps(await runUp(await loadMigration(content, 'ts')));
    const position = (pattern: RegExp): number =>
      sql.findIndex((statement) => pattern.test(statement));
    const created = [
      position(/^create sequence (public \. )?a_id_seq\b/),
      position(/^create (or replace )?function (public \. )?next_code\b/),
      position(/^create table (public \. )?a \(/),
      position(
        /^alter sequence (public \. )?a_id_seq owned by (public \. )?a \. id$/
      ),
    ];

    expect(created).not.toContain(-1);
    expect(created).toStrictEqual(created.toSorted((a, b) => a - b));
    expect(sql[created[2]]).not.toMatch(/\bserial\b/);
  });

  it('reports the comments on columns, domain constraints and the indexes of constraints by what they are on', () => {
    const orders = makeTable('public', 'orders');
    const view = makeView('app', 'v', ' SELECT 1 AS n', {
      columns: [{ name: 'n', comment: 'N' }],
    });
    const model = modelOf([
      orders,
      view,
      makeComposite('app', 'pair', [{ name: 'a', type: 'text', comment: 'A' }]),
      makeDomain('app', 'd', 'integer', {
        checks: [
          {
            name: 'd_check',
            expression: '(VALUE > 0)',
            validated: true,
            comment: 'Positive',
          },
        ],
      }),
      makeConstraint(orders, 'orders_pkey', 'primaryKey', 'PRIMARY KEY (id)', {
        comment: 'Key',
        indexComment: 'Index',
      }),
    ]);

    const { fallbacks } = generateMigration(model, OPTIONS);

    expect(fallbacks).toStrictEqual([
      {
        kind: 'comment',
        identity: 'd_check on app.d',
        reason: 'comment on constraint',
      },
      { kind: 'comment', identity: 'app.pair.a', reason: 'comment on column' },
      { kind: 'comment', identity: 'app.v.n', reason: 'comment on column' },
      {
        kind: 'comment',
        identity: 'orders_pkey on public.orders',
        reason: 'comment on constraint',
      },
      {
        kind: 'comment',
        identity: 'public.orders_pkey',
        reason: 'comment on index',
      },
    ]);
  });

  it('names the materialized views of a strict failure readably and counts identity columns once', () => {
    const measurements = makeTable('public', 'measurements', {
      partitioned: true,
      partitionKey: 'RANGE (id)',
      columns: [
        makeColumn('id', 'integer', {
          notNull: true,
          identity: {
            generation: 'ALWAYS',
            sequence: { schema: 'public', name: 'measurements_id_seq' },
            options: defaultSequenceOptions('integer'),
          },
        }),
      ],
    });
    const partition = makeTable('public', 'measurements_1', {
      partitionOf: {
        parent: { schema: 'public', name: 'measurements' },
        bound: 'FOR VALUES FROM (1) TO (10)',
      },
      columns: [
        makeColumn('id', 'integer', {
          notNull: true,
          local: false,
          inheritCount: 1,
        }),
      ],
    });
    const objects: ModelObject[] = [
      measurements,
      partition,
      makeMaterializedView('public', 'mv', ' SELECT 1 AS n', {
        options: ['fillfactor=50'],
      }),
    ];

    const { stats } = generateMigration(modelOf(objects), OPTIONS);
    const error = thrownBy(() =>
      generateMigration(modelOf(objects), {
        ...OPTIONS,
        language: 'js',
        strict: true,
      })
    );

    expect(stats).toMatchObject({
      tables: 2,
      sequences: 1,
      materializedViews: 1,
    });
    expect(error).toBeInstanceOf(BaselineError);
    expect(String(error)).toContain('--format js');
    expect(String(error)).toContain(
      'materialized view public.mv: storage parameters'
    );
    expect(String(error)).toContain('table public.measurements_1: partition');
  });

  it('says how many objects no migration can represent, for the language of the migration', () => {
    const error = thrownBy(() =>
      generateMigration(
        modelOf([], [], {
          unsupported: [{ kind: 'foreign table', identity: 'remote.rows' }],
        }),
        { ...OPTIONS, language: 'js' }
      )
    );

    expect(error).toMatchObject({ code: 'UNSUPPORTED_OBJECTS' });
    expect(String(error)).toContain(
      'A --format js baseline cannot represent 1 object(s)'
    );
    expect(String(error)).toContain('foreign table remote.rows');
  });
});
