-- Kitchen sink, family: tables. Identity columns (ALWAYS, BY DEFAULT with
-- options), serial and bigserial, generated stored columns, defaults (a
-- sequence, a domain, CURRENT_DATE), CHECK constraints (one NOT VALID),
-- foreign keys (self-reference, composite with MATCH FULL, deferrable,
-- across schemas), column collations, per-column statistics and storage, an
-- UNLOGGED table, storage parameters and an exclusion constraint that needs
-- btree_gist.

CREATE TABLE kitchen.customers (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    legacy_no serial NOT NULL UNIQUE,
    first_name text NOT NULL,
    last_name text NOT NULL,
    full_name text GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED,
    email kitchen.email_address,
    mood kitchen.mood NOT NULL DEFAULT 'ok',
    home kitchen.postal_address,
    code text COLLATE "C" CHECK (code ~ '^[A-Z]{3}[0-9]{2}$'),
    nickname text COLLATE kitchen.bytewise,
    referred_by bigint REFERENCES kitchen.customers (id) ON DELETE SET NULL,
    tags text[] NOT NULL DEFAULT '{}',
    settings jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz
);

ALTER TABLE kitchen.customers ALTER COLUMN email SET STATISTICS 500;

CREATE TABLE kitchen.products (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5) PRIMARY KEY,
    sku text NOT NULL CONSTRAINT products_sku_key UNIQUE,
    name text NOT NULL,
    price kitchen.money_amount,
    discount_pct numeric(5,2) NOT NULL DEFAULT 0 CHECK (discount_pct BETWEEN 0 AND 100),
    net_price numeric(12,2) GENERATED ALWAYS AS (round(price * (1 - discount_pct / 100), 2)) STORED,
    weight_grams integer,
    updated_at timestamptz
) WITH (fillfactor = 90);

ALTER TABLE kitchen.products
    ADD CONSTRAINT products_weight_positive CHECK (weight_grams > 0) NOT VALID;

CREATE TABLE kitchen.orders (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL REFERENCES kitchen.customers (id) ON DELETE CASCADE,
    status kitchen.order_status NOT NULL DEFAULT 'new',
    total kitchen.money_amount,
    ticket_no bigint NOT NULL DEFAULT nextval('kitchen.ticket_seq'),
    invoice_no integer DEFAULT nextval('kitchen.invoice_number'),
    placed_at timestamptz NOT NULL DEFAULT now(),
    shipped_at timestamptz,
    CONSTRAINT orders_shipped_after_placed CHECK (shipped_at IS NULL OR shipped_at >= placed_at)
);

ALTER SEQUENCE kitchen.ticket_seq OWNED BY kitchen.orders.ticket_no;

CREATE TABLE kitchen.order_lines (
    order_id bigint NOT NULL,
    line_no smallint NOT NULL,
    product_id integer NOT NULL REFERENCES kitchen.products (id),
    quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
    PRIMARY KEY (order_id, line_no),
    CONSTRAINT order_lines_order_fkey FOREIGN KEY (order_id)
        REFERENCES kitchen.orders (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE kitchen.shipments (
    id bigserial PRIMARY KEY,
    order_id bigint NOT NULL,
    line_no smallint NOT NULL,
    carrier text NOT NULL DEFAULT 'post',
    shipped_on date NOT NULL DEFAULT CURRENT_DATE,
    FOREIGN KEY (order_id, line_no) REFERENCES kitchen.order_lines (order_id, line_no)
        MATCH FULL ON UPDATE CASCADE
);

CREATE UNLOGGED TABLE kitchen.session_cache (
    key text PRIMARY KEY,
    value jsonb,
    expires_at timestamptz
) WITH (fillfactor = 70, autovacuum_enabled = false);

ALTER TABLE kitchen.session_cache ALTER COLUMN value SET STORAGE EXTERNAL;

CREATE TABLE kitchen.room_bookings (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    room_id integer NOT NULL,
    during tstzrange NOT NULL,
    booked_by bigint REFERENCES kitchen.customers (id),
    CONSTRAINT room_bookings_no_overlap EXCLUDE USING gist (room_id WITH =, during WITH &&)
);

CREATE TABLE kitchen_audit.events (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    table_name text NOT NULL,
    operation text NOT NULL,
    row_count bigint NOT NULL,
    logged_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
