-- Kitchen sink, family: row-level security. ENABLE and FORCE, a policy for
-- all commands with USING and WITH CHECK, a permissive SELECT policy and a
-- restrictive DELETE policy. The tenant default comes from a function in
-- 04-functions.sql.

CREATE TABLE kitchen.documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id integer NOT NULL DEFAULT kitchen.current_tenant(),
    owner_name name NOT NULL DEFAULT CURRENT_USER,
    title text NOT NULL,
    body text,
    is_public boolean NOT NULL DEFAULT false
);

ALTER TABLE kitchen.documents ENABLE ROW LEVEL SECURITY;

ALTER TABLE kitchen.documents FORCE ROW LEVEL SECURITY;

CREATE POLICY documents_tenant_isolation ON kitchen.documents
    USING (tenant_id = kitchen.current_tenant())
    WITH CHECK (tenant_id = kitchen.current_tenant());

CREATE POLICY documents_public_read ON kitchen.documents
    AS PERMISSIVE FOR SELECT
    USING (is_public);

CREATE POLICY documents_owner_delete ON kitchen.documents
    AS RESTRICTIVE FOR DELETE
    USING (owner_name = CURRENT_USER);
