-- Kitchen sink, family: identifiers and literals that need quoting. Every
-- semicolon, --, /* */, $$ and backslash below is inside double or single
-- quotes, so it is part of the statement around it. The comment on the table
-- spans three lines and its second line starts with a backslash.

CREATE SCHEMA "Sink Área";

CREATE TABLE "Sink Área"."Order; Lines" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "select" text NOT NULL DEFAULT 'semi; colon -- not a comment /* nor this */',
    "a ""quoted"" column" text,
    "$$not a dollar quote$$" text,
    "-- not a comment" integer CHECK ("-- not a comment" >= 0)
);

CREATE INDEX "Order; Lines ""select"" idx" ON "Sink Área"."Order; Lines" ("select");

CREATE VIEW "Sink Área"."From; View" AS
    SELECT "Id", "select" AS "from" FROM "Sink Área"."Order; Lines";

COMMENT ON TABLE "Sink Área"."Order; Lines" IS 'First line;
\connect is only text here, inside a string literal
It''s one string: $$ -- /* */';
