import { generateMigration } from '../../codegen';
import type { Fallback } from '../../codegen/fallback';
import { introspect } from '../../introspect/io/introspect';
import type { CatalogConnection } from '../../introspect/types';
import { formatFakeCommand } from '../core/fakeCommand';
import { estimateRelations } from '../core/locks';
import type { CatalogSettings, SchemaSettings } from '../core/plan';
import {
  assertCanBaseline,
  assertDecamelizeKeepsNames,
  fallbackWarnings,
  locksNeeded,
  migrationsObjects,
} from '../core/plan';
import type { DumpSource } from '../source';
import type { BaselineResult } from '../types';
import { assertIncludedSchemasExist, readServerFacts } from './server';

// A TypeScript or JavaScript baseline, generated from the catalogs of a
// database: what both `baseline()` (`format` `'ts'` or `'js'`) and the
// Node.js-free entry `node-pg-migrate/baseline/catalogs`
// (`src/baseline/catalogs.ts`) run, so that both generate the same migration.
// Like the entry, this module must only import modules that run anywhere (see
// test/baseline/catalogs.bundle.spec.ts).

/**
 * A TypeScript or JavaScript baseline generated by
 * {@link generateCatalogBaseline}: what `baseline()` returns about it, without
 * the file path, and the content of the file.
 */
export interface CatalogBaseline extends Omit<
  BaselineResult,
  'path' | 'fallbacks'
> {
  /**
   * The content of the migration file.
   */
  readonly content: string;

  /**
   * The objects the migration creates with raw SQL (`pgm.sql(…)`), in the
   * order of the migration; empty when there are none.
   */
  readonly fallbacks: ReadonlyArray<Fallback>;
}

/**
 * Generates a TypeScript or JavaScript baseline from the catalogs of a
 * database.
 *
 * It reads the facts of the server and refuses one that cannot get a
 * baseline (see `readServerFacts()` and `assertCanBaseline()`) and
 * `includeSchemas` that name no schema, then reads the schema from the
 * catalogs (see `introspect()`), refuses identifiers that `decamelize` would
 * rename, and generates the `pgm` calls (see `generateMigration()`). Every
 * refusal is a `BaselineError`. Nothing is written or logged.
 *
 * The connection must not be in a transaction: each read runs in one of its
 * own, which it rolls back.
 *
 * @param db The database.
 * @param settings The schemas of node-pg-migrate, and the migrations
 * directory, as the user gives it to node-pg-migrate (the `--fake` command
 * names it).
 * @param catalog How to read the catalogs, the language of the migration and
 * what to refuse.
 * @param migrationName The migration name (the file name without its
 * extension).
 * @returns The migration, and what the user should know about it.
 */
export async function generateCatalogBaseline(
  db: CatalogConnection,
  settings: SchemaSettings & { readonly dir: string },
  catalog: CatalogSettings,
  migrationName: string
): Promise<CatalogBaseline> {
  const facts = await readServerFacts(db, settings, { requireTable: true });
  assertCanBaseline(facts, settings);
  await assertIncludedSchemasExist(db, catalog.includeSchemas ?? []);
  const model = await introspect(db, {
    includeSchemas: catalog.includeSchemas,
    excludeSchemas: catalog.excludeSchemas,
    migrationsSchema: settings.migrationsSchema,
    migrationsTable: settings.migrationsTable,
    migrationsSequence: migrationsObjects(settings, facts).sequence,
  });
  assertDecamelizeKeepsNames(model, catalog.decamelize);

  const fakeCommand = formatFakeCommand(migrationName, settings.dir, {
    migrationsTable: settings.migrationsTable,
    migrationsSchema: settings.migrationsSchema,
  });
  const source: DumpSource = { serverVersion: facts.version };
  const generated = generateMigration(model, {
    language: catalog.language,
    defaultSchema: settings.createdSchemas[0],
    strict: catalog.strict,
    migrationName,
    fakeCommand,
    source,
    maxConnections: facts.maxConnections,
    maxPreparedTransactions: facts.maxPreparedTransactions,
  });
  const relations = estimateRelations(generated.stats);
  const { warnings: lockWarnings, ...locks } = locksNeeded(relations, facts);

  return {
    content: generated.content,
    migrationName,
    fakeCommand,
    relations,
    ...locks,
    warnings: [
      ...fallbackWarnings(generated.fallbacks.length),
      ...lockWarnings,
    ],
    source,
    fallbacks: generated.fallbacks,
  };
}
