import { describe, expect, it } from 'vitest';
import { emitTable } from '../../../src/codegen/emitters/tables';
import type { Column } from '../../../src/introspect/types';
import {
  defaultSequenceOptions,
  makeColumn,
  makeTable,
} from '../../introspect/objects';
import { expectFallback, expectSql } from '../expectations';
import { emitAndRun } from '../run';

// `createTable` cannot set the comment on the sequence of an identity
// column, which `COMMENT ON SEQUENCE` sets right after the table.

/**
 * An identity column whose sequence has a comment.
 */
function identity(comment?: string): Column {
  return makeColumn('id', 'integer', {
    notNull: true,
    identity: {
      generation: 'BY DEFAULT',
      sequence: { schema: 'kitchen', name: 'tickets_id_seq' },
      options: defaultSequenceOptions('integer'),
      ...(comment === undefined ? {} : { comment }),
    },
  });
}

const COMMENT =
  'COMMENT ON SEQUENCE "kitchen"."tickets_id_seq" IS \'Ticket numbers\';';

describe('emitTable', () => {
  it('sets the comment on an identity sequence after createTable', () => {
    const result = emitAndRun(
      emitTable,
      makeTable('kitchen', 'tickets', {
        columns: [identity('Ticket numbers')],
      })
    );

    expectFallback(result, 'comment on sequence');
    expect(result.calls).toStrictEqual(['createTable', 'sql']);
    expectSql(
      result,
      [
        'CREATE TABLE "kitchen"."tickets" ("id" integer GENERATED BY DEFAULT AS IDENTITY);',
        COMMENT,
      ].join('\n')
    );
  });

  it('gives the reasons of the comments on an inherited column and on an identity sequence in order', () => {
    const result = emitAndRun(
      emitTable,
      makeTable('kitchen', 'tickets', {
        inherits: [{ schema: 'kitchen', name: 'documents' }],
        columns: [
          makeColumn('title', 'text', {
            local: false,
            inheritCount: 1,
            comment: 'Inherited',
          }),
          identity('Ticket numbers'),
        ],
      })
    );

    expectFallback(result, 'comment on column', 'comment on sequence');
  });

  it('adds the comment to a whole-table fallback without another reason', () => {
    const result = emitAndRun(
      emitTable,
      makeTable('kitchen', 'tickets', {
        options: ['fillfactor=90'],
        columns: [identity('Ticket numbers')],
      })
    );

    expectFallback(result, 'storage parameters');
    expectSql(
      result,
      [
        'CREATE TABLE "kitchen"."tickets" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL) WITH (fillfactor=90);',
        COMMENT,
      ].join('\n')
    );
  });

  it('writes nothing more for an identity sequence without a comment', () => {
    const result = emitAndRun(
      emitTable,
      makeTable('kitchen', 'tickets', { columns: [identity()] })
    );

    expect(result.emitted.kind).toBe('code');
    expect(result.calls).toStrictEqual(['createTable']);
  });
});
