import { describe, expect, it } from 'vitest';
import { emitTable } from '../../../src/codegen/emitters/tables';
import type { Column } from '../../../src/introspect/types';
import {
  defaultSequenceOptions,
  makeColumn,
  makeTable,
} from '../../introspect/objects';
import { expectCode, expectSql, expectSqlThenAnyOrder } from '../expectations';
import { emitAndRun } from '../run';

function serialColumn(
  name: string,
  type: 'smallint' | 'integer' | 'bigint',
  fields: Partial<Column> = {}
): Column {
  const sequence = `users_${name}_seq`;

  return makeColumn(name, type, {
    notNull: true,
    default: `nextval('public.${sequence}'::regclass)`,
    ownedSequence: {
      name: { schema: 'public', name: sequence },
      options: defaultSequenceOptions(type),
      unlogged: false,
    },
    ...fields,
  });
}

describe('emitTable', () => {
  it('creates a table with pgm.createTable, its defaults with pgm.func and its comments', () => {
    const table = makeTable('public', 'orders', {
      comment: 'Orders',
      columns: [
        makeColumn('id', 'bigint', {
          notNull: true,
          identity: {
            generation: 'ALWAYS',
            sequence: { schema: 'public', name: 'orders_id_seq' },
            options: defaultSequenceOptions('bigint'),
          },
        }),
        makeColumn('customer_id', 'bigint', { notNull: true }),
        makeColumn('status', 'text', { notNull: true, default: "'new'::text" }),
        makeColumn('note', 'text', {
          collation: 'pg_catalog."C"',
          comment: "Free text, it's optional",
        }),
        makeColumn('total', 'numeric(12,2)', {
          generated: { storage: 'STORED', expression: '(qty * price)' },
        }),
        makeColumn('placed_at', 'timestamp with time zone', {
          notNull: true,
          default: 'now()',
        }),
      ],
    });
    const result = emitAndRun(emitTable, table);

    expectCode(result);
    expect(result.calls).toStrictEqual(['createTable']);
    expect(result.funcs.toSorted()).toStrictEqual(["'new'::text", 'now()']);
    expectSqlThenAnyOrder(
      result,
      `CREATE TABLE "orders" (
         "id" bigint GENERATED ALWAYS AS IDENTITY,
         "customer_id" bigint NOT NULL,
         "status" text DEFAULT 'new'::text NOT NULL,
         "note" text COLLATE pg_catalog."C",
         "total" numeric(12,2) GENERATED ALWAYS AS ((qty * price)) STORED,
         "placed_at" timestamp with time zone DEFAULT now() NOT NULL
       );
       COMMENT ON TABLE "orders" IS 'Orders';
       COMMENT ON COLUMN "orders"."note" IS 'Free text, it''s optional';`
    );
  });

  it('writes the options of an identity sequence', () => {
    const result = emitAndRun(
      emitTable,
      makeTable('public', 'products', {
        columns: [
          makeColumn('id', 'integer', {
            notNull: true,
            identity: {
              generation: 'BY DEFAULT',
              sequence: { schema: 'public', name: 'products_id_seq' },
              options: defaultSequenceOptions('integer', {
                start: '100',
                increment: '5',
              }),
            },
          }),
        ],
      })
    );

    expectCode(result);
    expectSql(
      result,
      'CREATE TABLE "products" ("id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5));'
    );
  });

  it('writes serial columns for sequences that serial would have created', () => {
    const result = emitAndRun(
      emitTable,
      makeTable('public', 'users', {
        columns: [
          serialColumn('id', 'integer'),
          serialColumn('big', 'bigint'),
          serialColumn('small', 'smallint'),
        ],
      })
    );

    expectCode(result);
    expect(result.funcs).toStrictEqual([]);
    expectSql(
      result,
      'CREATE TABLE "users" ("id" serial, "big" bigserial, "small" smallserial);'
    );
  });

  it('writes a serial column of a table whose names need quotes', () => {
    const sequence = 'Order Items_Line No_seq';
    const result = emitAndRun(
      emitTable,
      makeTable('public', 'Order Items', {
        columns: [
          makeColumn('Line No', 'integer', {
            notNull: true,
            default: `nextval('public."${sequence}"'::regclass)`,
            ownedSequence: {
              name: { schema: 'public', name: sequence },
              options: defaultSequenceOptions('integer'),
              unlogged: false,
            },
          }),
        ],
      })
    );

    expectCode(result);
    expectSql(result, 'CREATE TABLE "Order Items" ("Line No" serial);');
  });

  it.each<[string, Partial<Column>, string]>([
    [
      'its sequence is not named <table>_<column>_seq',
      {
        default: "nextval('public.user_ids'::regclass)",
        ownedSequence: {
          name: { schema: 'public', name: 'user_ids' },
          options: defaultSequenceOptions('integer'),
          unlogged: false,
        },
      },
      `"id" integer DEFAULT nextval('public.user_ids'::regclass) NOT NULL`,
    ],
    [
      'its sequence is in another schema',
      {
        default: "nextval('kitchen.users_id_seq'::regclass)",
        ownedSequence: {
          name: { schema: 'kitchen', name: 'users_id_seq' },
          options: defaultSequenceOptions('integer'),
          unlogged: false,
        },
      },
      `"id" integer DEFAULT nextval('kitchen.users_id_seq'::regclass) NOT NULL`,
    ],
    [
      'its sequence has options that are not the default',
      {
        ownedSequence: {
          name: { schema: 'public', name: 'users_id_seq' },
          options: defaultSequenceOptions('integer', { start: '100' }),
          unlogged: false,
        },
      },
      `"id" integer DEFAULT nextval('public.users_id_seq'::regclass) NOT NULL`,
    ],
    [
      'its sequence has another type',
      {
        ownedSequence: {
          name: { schema: 'public', name: 'users_id_seq' },
          options: defaultSequenceOptions('bigint'),
          unlogged: false,
        },
      },
      `"id" integer DEFAULT nextval('public.users_id_seq'::regclass) NOT NULL`,
    ],
    [
      'its sequence is unlogged and the table is not',
      {
        ownedSequence: {
          name: { schema: 'public', name: 'users_id_seq' },
          options: defaultSequenceOptions('integer'),
          unlogged: true,
        },
      },
      `"id" integer DEFAULT nextval('public.users_id_seq'::regclass) NOT NULL`,
    ],
    [
      'it is nullable',
      { notNull: false },
      `"id" integer DEFAULT nextval('public.users_id_seq'::regclass)`,
    ],
    [
      'its default does not use its sequence',
      { default: "nextval('public.other_seq'::regclass)" },
      `"id" integer DEFAULT nextval('public.other_seq'::regclass) NOT NULL`,
    ],
  ])('keeps the default of a column when %s', (_, fields, column) => {
    const result = emitAndRun(
      emitTable,
      makeTable('public', 'users', {
        columns: [serialColumn('id', 'integer', fields)],
      })
    );

    expectCode(result);
    expect(result.funcs).toHaveLength(1);
    expectSql(result, `CREATE TABLE "users" (${column});`);
  });

  it('keeps idiomatic an inherited NOT NULL constraint that has the name its parent gave it', () => {
    const result = emitAndRun(
      emitTable,
      makeTable('public', 'trucks', {
        inherits: [{ schema: 'kitchen', name: 'vehicles' }],
        columns: [
          makeColumn('id', 'integer', {
            notNull: true,
            local: false,
            inheritCount: 1,
            notNullConstraint: {
              name: 'vehicles_id_not_null',
              noInherit: false,
              validated: true,
            },
          }),
          makeColumn('wheels', 'integer'),
        ],
      })
    );

    expectCode(result);
    expectSql(
      result,
      'CREATE TABLE "trucks" ("wheels" integer) INHERITS ("kitchen"."vehicles");'
    );
  });

  it('lists only the local columns of an inheritance child', () => {
    const result = emitAndRun(
      emitTable,
      makeTable('public', 'trucks', {
        inherits: [{ schema: 'kitchen', name: 'vehicles' }],
        columns: [
          makeColumn('id', 'integer', { local: false, inheritCount: 1 }),
          makeColumn('plate', 'text', { local: true, inheritCount: 1 }),
          makeColumn('wheels', 'integer'),
        ],
      })
    );

    expectCode(result);
    expectSql(
      result,
      'CREATE TABLE "trucks" ("plate" text, "wheels" integer) INHERITS ("kitchen"."vehicles");'
    );
  });

  it.each([
    ['RANGE (measured_at)', 'RANGE ("measured_at")'],
    ['LIST (region)', 'LIST ("region")'],
    ['HASH (order_id)', 'HASH ("order_id")'],
    ['RANGE (region, measured_at)', 'RANGE ("region", "measured_at")'],
  ])('creates a table partitioned by %s', (partitionKey, expected) => {
    const result = emitAndRun(
      emitTable,
      makeTable('public', 'events', {
        partitioned: true,
        partitionKey,
        columns: [
          makeColumn('region', 'text'),
          makeColumn('order_id', 'bigint'),
          makeColumn('measured_at', 'timestamp with time zone'),
        ],
      })
    );

    expectCode(result);
    expectSql(
      result,
      `CREATE TABLE "events" ("region" text, "order_id" bigint, "measured_at" timestamp with time zone) PARTITION BY ${expected};`
    );
  });

  it('creates an unlogged table of another schema', () => {
    const result = emitAndRun(
      emitTable,
      makeTable('kitchen', 'session_cache', {
        unlogged: true,
        columns: [makeColumn('key', 'text', { notNull: true })],
      })
    );

    expectCode(result);
    expectSql(
      result,
      'CREATE UNLOGGED TABLE "kitchen"."session_cache" ("key" text NOT NULL);'
    );
  });

  it('keeps idiomatic a NOT NULL constraint with its default name, row-level security and a replica identity index', () => {
    const result = emitAndRun(
      emitTable,
      makeTable('kitchen', 'parcels', {
        rowLevelSecurity: true,
        forceRowLevelSecurity: true,
        replicaIdentity: 'INDEX',
        columns: [
          makeColumn('width', 'integer', {
            notNull: true,
            notNullConstraint: {
              name: 'parcels_width_not_null',
              noInherit: false,
              validated: true,
            },
          }),
        ],
      })
    );

    expectCode(result);
    expectSql(
      result,
      'CREATE TABLE "kitchen"."parcels" ("width" integer NOT NULL);'
    );
  });
});
