import { describe, expect, it } from 'vitest';
import {
  emitTable,
  serialSequences,
} from '../../../src/codegen/emitters/tables';
import type { Column, Table } from '../../../src/introspect/types';
import {
  defaultSequenceOptions,
  makeColumn,
  makeTable,
} from '../../introspect/objects';
import {
  expectCode,
  expectFallback,
  expectSql,
  expectSqlThenAnyOrder,
} from '../expectations';
import type { EmitResult } from '../run';
import { emitAndRun } from '../run';

// What `createTable` cannot write faithfully (CONTRACT-TS.md §11), and the
// columns of whole-table fallbacks.

type TableFields = Partial<Omit<Table, 'kind'>>;

function onlyRawSql(result: EmitResult): void {
  expect(new Set(result.calls)).toStrictEqual(new Set(['sql']));
}

function identityColumn(
  name: string,
  options: Parameters<typeof defaultSequenceOptions>[1]
): Column {
  return makeColumn(name, 'integer', {
    notNull: true,
    identity: {
      generation: 'ALWAYS',
      sequence: { schema: 'kitchen', name: `t_${name}_seq` },
      options: defaultSequenceOptions('integer', options),
    },
  });
}

function serial(
  table: string,
  column: string,
  fields: Partial<Column> = {}
): Column {
  const sequence = `${table}_${column}_seq`;

  return makeColumn(column, 'integer', {
    notNull: true,
    default: `nextval('kitchen.${sequence}'::regclass)`,
    ownedSequence: {
      name: { schema: 'kitchen', name: sequence },
      options: defaultSequenceOptions('integer'),
      unlogged: false,
    },
    ...fields,
  });
}

describe('emitTable', () => {
  it.each<[string, string, TableFields, string]>([
    [
      'a zero in the options of an identity column',
      'zero option',
      { columns: [identityColumn('id', { minValue: '0', start: '0' })] },
      'CREATE TABLE "kitchen"."t" ("id" integer GENERATED ALWAYS AS IDENTITY (MINVALUE 0));',
    ],
    [
      'identity options beyond the safe integers',
      'bigint option',
      {
        columns: [
          makeColumn('id', 'bigint', {
            notNull: true,
            identity: {
              generation: 'BY DEFAULT',
              sequence: { schema: 'kitchen', name: 't_id_seq' },
              options: defaultSequenceOptions('bigint', {
                start: '9007199254740993',
              }),
            },
          }),
        ],
      },
      'CREATE TABLE "kitchen"."t" ("id" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 9007199254740993));',
    ],
    [
      'integer-like column names, which an object would put first',
      'column order',
      {
        columns: [
          makeColumn('b', 'text'),
          makeColumn('2', 'integer'),
          makeColumn('1', 'integer'),
        ],
      },
      'CREATE TABLE "kitchen"."t" ("b" text, "2" integer, "1" integer);',
    ],
    [
      'no column of its own',
      'no columns',
      {
        inherits: [{ schema: 'kitchen', name: 'vehicles' }],
        columns: [
          makeColumn('id', 'integer', { local: false, inheritCount: 1 }),
        ],
      },
      'CREATE TABLE "kitchen"."t" () INHERITS ("kitchen"."vehicles");',
    ],
    [
      'an expression in its partition key',
      'partition key',
      {
        partitioned: true,
        partitionKey: 'LIST (lower(name))',
        columns: [makeColumn('name', 'text')],
      },
      'CREATE TABLE "kitchen"."t" ("name" text) PARTITION BY LIST (lower(name));',
    ],
    [
      'a parenthesized expression in its partition key',
      'partition key',
      {
        partitioned: true,
        partitionKey: 'RANGE ((a + b))',
        columns: [makeColumn('a', 'integer'), makeColumn('b', 'integer')],
      },
      'CREATE TABLE "kitchen"."t" ("a" integer, "b" integer) PARTITION BY RANGE ((a + b));',
    ],
    [
      'a partition key that is not RANGE, LIST or HASH',
      'partition key',
      {
        partitioned: true,
        partitionKey: 'SPLIT (a)',
        columns: [makeColumn('a', 'integer')],
      },
      'CREATE TABLE "kitchen"."t" ("a" integer) PARTITION BY SPLIT (a);',
    ],
    [
      'a collation in its partition key',
      'partition key',
      {
        partitioned: true,
        partitionKey: 'RANGE (name COLLATE "C")',
        columns: [makeColumn('name', 'text')],
      },
      'CREATE TABLE "kitchen"."t" ("name" text) PARTITION BY RANGE (name COLLATE "C");',
    ],
    [
      'an operator class in its partition key',
      'partition key',
      {
        partitioned: true,
        partitionKey: 'RANGE (name text_pattern_ops)',
        columns: [makeColumn('name', 'text')],
      },
      'CREATE TABLE "kitchen"."t" ("name" text) PARTITION BY RANGE (name text_pattern_ops);',
    ],
    [
      'a NO INHERIT NOT NULL constraint',
      'NOT NULL NO INHERIT',
      {
        columns: [
          makeColumn('a', 'integer', {
            notNull: true,
            notNullConstraint: {
              name: 't_a_not_null',
              noInherit: true,
              validated: true,
            },
          }),
        ],
      },
      'CREATE TABLE "kitchen"."t" ("a" integer NOT NULL NO INHERIT);',
    ],
    [
      'a column default with a line break',
      'line break',
      {
        columns: [makeColumn('note', 'text', { default: "'one\ntwo'::text" })],
      },
      `CREATE TABLE "kitchen"."t" ("note" text DEFAULT 'one\ntwo'::text);`,
    ],
  ])(
    'creates a table with %s with CREATE TABLE',
    (_, reason, fields, expected) => {
      const result = emitAndRun(emitTable, makeTable('kitchen', 't', fields));

      expectFallback(result, reason);
      onlyRawSql(result);
      expectSql(result, expected);
    }
  );

  it('adds a NOT VALID NOT NULL constraint after creating the table', () => {
    const result = emitAndRun(
      emitTable,
      makeTable('kitchen', 't', {
        columns: [
          makeColumn('a', 'integer', {
            notNull: true,
            notNullConstraint: {
              name: 'a_checked_later',
              noInherit: true,
              validated: false,
            },
          }),
        ],
      })
    );

    expectFallback(
      result,
      'NOT NULL constraint name',
      'NOT NULL NO INHERIT',
      'NOT NULL NOT VALID'
    );
    expectSql(
      result,
      `CREATE TABLE "kitchen"."t" ("a" integer);
       ALTER TABLE "kitchen"."t" ADD CONSTRAINT "a_checked_later" NOT NULL "a" NO INHERIT NOT VALID;`
    );
  });

  it('keeps the columns of a partition with WITH OPTIONS: their defaults and named NOT NULL constraints', () => {
    const inherited = { local: false, inheritCount: 1 };
    const result = emitAndRun(
      emitTable,
      makeTable('kitchen', 'm_2025', {
        unlogged: true,
        partitionOf: {
          parent: { schema: 'kitchen', name: 'm' },
          bound: 'FOR VALUES FROM (1) TO (10)',
        },
        columns: [
          makeColumn('id', 'integer', {
            ...inherited,
            notNull: true,
            default: "nextval('kitchen.m_id_seq'::regclass)",
            notNullConstraint: {
              name: 'm_2025_id_not_null',
              noInherit: false,
              validated: true,
            },
          }),
          makeColumn('at', 'date', { ...inherited, notNull: true }),
          makeColumn('value', 'numeric', {
            ...inherited,
            comment: 'Value',
            statisticsTarget: 10,
          }),
        ],
      })
    );

    expectFallback(result, 'partition', 'column settings');
    onlyRawSql(result);
    expectSqlThenAnyOrder(
      result,
      `CREATE UNLOGGED TABLE "kitchen"."m_2025" PARTITION OF "kitchen"."m" (
         "id" WITH OPTIONS DEFAULT nextval('kitchen.m_id_seq'::regclass) CONSTRAINT "m_2025_id_not_null" NOT NULL,
         "at" WITH OPTIONS NOT NULL
       ) FOR VALUES FROM (1) TO (10);
       ALTER TABLE "kitchen"."m_2025" ALTER COLUMN "value" SET STATISTICS 10;
       COMMENT ON COLUMN "kitchen"."m_2025"."value" IS 'Value';`
    );
  });

  it('writes a serial column of a whole-table fallback with its default, and creates no serial', () => {
    const table = makeTable('kitchen', 'customers', {
      options: ['fillfactor=90'],
      columns: [serial('customers', 'legacy_no')],
    });
    const result = emitAndRun(emitTable, table);

    expectFallback(result, 'storage parameters');
    expectSql(
      result,
      `CREATE TABLE "kitchen"."customers" (
         "legacy_no" integer DEFAULT nextval('kitchen.customers_legacy_no_seq'::regclass) NOT NULL
       ) WITH (fillfactor = 90);`
    );
    expect(serialSequences(table)).toStrictEqual([]);
  });

  it('lists the sequences of the serial columns it creates', () => {
    const table = makeTable('kitchen', 'customers', {
      columns: [
        serial('customers', 'legacy_no', { comment: 'Old number' }),
        serial('customers', 'other', {
          default: "nextval('kitchen.somewhere_else'::regclass)",
        }),
      ],
    });
    const result = emitAndRun(emitTable, table);

    expectCode(result);
    expectSqlThenAnyOrder(
      result,
      `CREATE TABLE "kitchen"."customers" (
         "legacy_no" serial,
         "other" integer DEFAULT nextval('kitchen.somewhere_else'::regclass) NOT NULL
       );
       COMMENT ON COLUMN "kitchen"."customers"."legacy_no" IS 'Old number';`
    );
    expect(serialSequences(table)).toStrictEqual([
      { schema: 'kitchen', name: 'customers_legacy_no_seq' },
    ]);
  });

  it('writes serial for the truncated sequence name of long names', () => {
    const tableName = 'a'.repeat(40);
    const columnName = 'b'.repeat(40);
    const sequence = `${'a'.repeat(29)}_${'b'.repeat(29)}_seq`;
    const table = makeTable('kitchen', tableName, {
      columns: [
        makeColumn(columnName, 'bigint', {
          notNull: true,
          default: `nextval('kitchen.${sequence}'::regclass)`,
          ownedSequence: {
            name: { schema: 'kitchen', name: sequence },
            options: defaultSequenceOptions('bigint'),
            unlogged: false,
          },
        }),
      ],
    });

    expectCode(emitAndRun(emitTable, table));
    expect(serialSequences(table)).toStrictEqual([
      { schema: 'kitchen', name: sequence },
    ]);
  });

  it('sets the comments of the columns an inheritance child only inherits after creating it', () => {
    const result = emitAndRun(
      emitTable,
      makeTable('public', 'trucks', {
        inherits: [{ schema: 'public', name: 'vehicles' }],
        columns: [
          makeColumn('plate', 'text', {
            local: false,
            inheritCount: 1,
            comment: "The truck's plate",
          }),
          makeColumn('payload', 'integer'),
        ],
      })
    );

    expectFallback(result, 'comment on column');
    expect(result.calls).toStrictEqual(['createTable', 'sql']);
    expectSql(
      result,
      `CREATE TABLE "trucks" ("payload" integer) INHERITS ("vehicles");
       COMMENT ON COLUMN "public"."trucks"."plate" IS 'The truck''s plate';`
    );
  });

  it('keeps the names of columns and partition keys that need quotes', () => {
    const result = emitAndRun(
      emitTable,
      makeTable('public', 'events', {
        partitioned: true,
        partitionKey: 'RANGE ("Measured At", "a ""b""")',
        columns: [
          makeColumn('Measured At', 'date'),
          makeColumn('a "b"', 'integer'),
          makeColumn('__proto__', 'text', { notNull: true }),
        ],
      })
    );

    expectCode(result);
    expectSql(
      result,
      `CREATE TABLE "events" ("Measured At" date, "a ""b""" integer, "__proto__" text NOT NULL)
       PARTITION BY RANGE ("Measured At", "a ""b""");`
    );
  });

  it('writes the collation, compression, storage and options of a whole-table fallback', () => {
    const result = emitAndRun(
      emitTable,
      makeTable('kitchen', 't', {
        accessMethod: 'heap2',
        options: ['toast_tuple_target=4096', 'autovacuum_enabled=off'],
        columns: [
          makeColumn('code', 'text', {
            collation: 'pg_catalog."C"',
            storage: 'MAIN',
            compression: 'pglz',
            options: ['n_distinct=-1', 'n_distinct_inherited=10'],
          }),
        ],
      })
    );

    expectFallback(
      result,
      'storage parameters',
      'access method',
      'column settings'
    );
    expectSqlThenAnyOrder(
      result,
      `CREATE TABLE "kitchen"."t" ("code" text COLLATE pg_catalog."C") USING heap2 WITH (toast_tuple_target = 4096, autovacuum_enabled = off);
       ALTER TABLE "kitchen"."t" ALTER COLUMN "code" SET STORAGE MAIN;
       ALTER TABLE "kitchen"."t" ALTER COLUMN "code" SET COMPRESSION pglz;
       ALTER TABLE "kitchen"."t" ALTER COLUMN "code" SET (n_distinct=-1, n_distinct_inherited=10);`
    );
  });

  it('writes an identity column and a NOT NULL constraint with their names in a whole-table fallback', () => {
    const result = emitAndRun(
      emitTable,
      makeTable('kitchen', 't', {
        replicaIdentity: 'FULL',
        columns: [
          makeColumn('id', 'integer', {
            notNull: true,
            notNullConstraint: {
              name: 'id_required',
              noInherit: false,
              validated: true,
            },
            identity: {
              generation: 'BY DEFAULT',
              sequence: { schema: 'app', name: 'ids' },
              options: defaultSequenceOptions('integer', { cache: '20' }),
            },
          }),
        ],
      })
    );

    expectFallback(
      result,
      'identity sequence name',
      'NOT NULL constraint name',
      'replica identity'
    );
    expectSqlThenAnyOrder(
      result,
      `CREATE TABLE "kitchen"."t" (
         "id" integer GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "app"."ids" CACHE 20) CONSTRAINT "id_required" NOT NULL
       );
       ALTER TABLE "kitchen"."t" REPLICA IDENTITY FULL;`
    );
  });
});
