import type { Emitted, RenderOptions } from './types';

/**
 * Writes the file of a generated migration: the header comment (generated by
 * `node-pg-migrate baseline`, experimental, where the schema came from, the
 * `--fake` command and the notes of `options.header`), then `up` with every
 * step in order (indented by 2 spaces, each fallback under a `// fallback:
 * <reason>` comment), then `down = false`.
 *
 * - `ts`: `import type { MigrationBuilder } from 'node-pg-migrate';`, `export
 *   const up = (pgm: MigrationBuilder): void => { … };` and `export const
 *   down = false;`.
 * - `js`: the same as an ES module with JSDoc types, in the style of
 *   `templates/migration-template.js`.
 *
 * The output has no timestamps: the same steps and options always give the
 * same file. It ends with a single `\n`.
 *
 * @param steps The code of each step, in order (the prologue and epilogue
 * included).
 * @param options The language and what the header says.
 * @returns The content of the migration file.
 */
export function renderMigration(
  _steps: ReadonlyArray<Emitted>,
  _options: RenderOptions
): string {
  throw new Error('not implemented');
}
