import { DEFAULT_MAX_LOCKS_PER_TRANSACTION } from '../baseline/core/locks';
import type { DumpSource, HeaderMeta } from '../baseline/types';
import type { Emitted, OutputLanguage, RenderOptions } from './types';

/**
 * Formats counts with thousands separators, like the SQL header.
 */
const COUNT_FORMAT = new Intl.NumberFormat('en-US');

/**
 * The characters that end a `//` comment in JavaScript.
 */
const LINE_TERMINATORS = /[\n\r\u2028\u2029]/g;

/**
 * Where the schema came from, worded like the SQL header: e.g. `PostgreSQL
 * 18.6` for a live server, `PostgreSQL 18.6 (pg_dump 18.6)` or `schema.sql
 * (PostgreSQL 16.4, pg_dump 16.4)`; unknown versions are left out.
 */
function describeSource(source: DumpSource): string {
  const server =
    source.serverVersion === undefined
      ? undefined
      : `PostgreSQL ${source.serverVersion}`;
  const pgDump =
    source.pgDumpVersion === undefined
      ? undefined
      : `pg_dump ${source.pgDumpVersion}`;
  if (source.file !== undefined) {
    const versions = [server, pgDump].filter((part) => part !== undefined);

    return versions.length === 0
      ? source.file
      : `${source.file} (${versions.join(', ')})`;
  }

  const origin = server ?? 'PostgreSQL';

  return pgDump === undefined ? origin : `${origin} (${pgDump})`;
}

/**
 * The lines of the header comment, without their `// `.
 */
function headerLines(language: OutputLanguage, meta: HeaderMeta): string[] {
  const lines = [
    `Baseline generated by \`node-pg-migrate baseline --format ${language}\` from ${describeSource(meta.source)}.`,
    `--format ${language} is experimental: review this migration before you rely on it.`,
    'On databases that already have this schema, record it without running it:',
    `  ${meta.fakeCommand}`,
    'Blank databases run it with a normal `node-pg-migrate up`.',
  ];
  if (meta.materializedViews > 0) {
    const views =
      meta.materializedViews === 1
        ? '1 materialized view'
        : `${COUNT_FORMAT.format(meta.materializedViews)} materialized views`;
    lines.push(
      `It creates ${views} WITH DATA, filled from the tables as they are when`,
      '  it runs: refresh them after loading data.'
    );
  }

  const locks = meta.requiredMaxLocksPerTransaction;
  if (locks !== undefined && locks > DEFAULT_MAX_LOCKS_PER_TRANSACTION) {
    lines.push(
      `It creates about ${COUNT_FORMAT.format(meta.relations)} relations in one transaction, so blank databases need`,
      `  max_locks_per_transaction = ${String(locks)} or more (the default is ${String(DEFAULT_MAX_LOCKS_PER_TRANSACTION)}).`
    );
  }

  return lines;
}

/**
 * The lines of `up`'s body: every step indented by two spaces, a blank line
 * between steps, and a `// fallback: <reason>` comment above each fallback.
 */
function bodyLines(steps: ReadonlyArray<Emitted>): string[] {
  return steps
    .flatMap((step, index) => [
      ...(index === 0 ? [] : ['']),
      ...(step.kind === 'fallback' ? [`// fallback: ${step.reason}`] : []),
      ...step.code.split('\n'),
    ])
    .map((line) => (line === '' ? line : `  ${line}`));
}

/**
 * Writes the file of a generated migration: the header comment (generated by
 * `node-pg-migrate baseline`, experimental, where the schema came from, the
 * `--fake` command and the notes of `options.header`), then `up` with every
 * step in order (indented by 2 spaces, each fallback under a `// fallback:
 * <reason>` comment), then `down = false`.
 *
 * - `ts`: `import type { MigrationBuilder } from 'node-pg-migrate';`, `export
 *   const up = (pgm: MigrationBuilder): void => { … };` and `export const
 *   down = false;`.
 * - `js`: the same as an ES module with JSDoc types, in the style of
 *   `templates/migration-template.js`.
 *
 * The notes say, when they apply, that the materialized views are created
 * with data (from the tables as they are when the migration runs) and how
 * large `max_locks_per_transaction` must be.
 *
 * The output has no timestamps: the same steps and options always give the
 * same file. It ends with a single `\n`.
 *
 * @param steps The code of each step, in order (the prologue and epilogue
 * included).
 * @param options The language and what the header says.
 * @returns The content of the migration file.
 */
export function renderMigration(
  steps: ReadonlyArray<Emitted>,
  options: RenderOptions
): string {
  const { language, header } = options;
  const comment = headerLines(language, header).map(
    (line) => `// ${line.replaceAll(LINE_TERMINATORS, ' ')}`
  );
  const up =
    language === 'ts'
      ? [
          "import type { MigrationBuilder } from 'node-pg-migrate';",
          '',
          'export const up = (pgm: MigrationBuilder): void => {',
        ]
      : [
          '/**',
          " * @param pgm {import('node-pg-migrate').MigrationBuilder}",
          ' * @returns {void}',
          ' */',
          'export const up = (pgm) => {',
        ];

  return `${[
    ...comment,
    '',
    ...up,
    ...bodyLines(steps),
    '};',
    '',
    'export const down = false;',
  ].join('\n')}\n`;
}
