import type { DumpSource, DumpStats, HeaderMeta } from '../baseline/types';
import type { Fallback } from './fallback';

export type { Fallback } from './fallback';

/**
 * The language of a generated migration.
 */
export type OutputLanguage = 'ts' | 'js';

/**
 * The code of one step of a generated migration.
 *
 * `code` is one or more complete statements (each ending with `;`, several
 * separated by `\n`), not indented: `renderMigration()` indents them inside
 * `up`. Strings in it are written with `tsString()`.
 */
export type Emitted =
  | {
      /**
       * Only `pgm` operations (e.g. `pgm.createTable(…);`).
       */
      readonly kind: 'code';
      readonly code: string;
    }
  | {
      /**
       * Raw SQL (`pgm.sql(…);`), possibly after `pgm` operations, because
       * the operations cannot express the whole object.
       */
      readonly kind: 'fallback';
      readonly code: string;

      /**
       * Why, e.g. `'partition'`: `renderMigration()` writes it as a
       * `// fallback: <reason>` comment above the code.
       */
      readonly reason: string;
    };

/**
 * What every emitter needs to know about the migration.
 */
export interface EmitContext {
  /**
   * The schema that names are relative to: `renderName()` leaves it out.
   * The first schema of the `schema` option, `public` by default.
   */
  readonly defaultSchema: string;

  /**
   * The language of the migration.
   */
  readonly language: OutputLanguage;
}

/**
 * Options of `renderMigration()`.
 */
export interface RenderOptions {
  /**
   * The language of the migration: `ts` (typed `up`, `import type {
   * MigrationBuilder }`) or `js` (ESM with JSDoc types, like
   * `templates/migration-template.js`).
   */
  readonly language: OutputLanguage;

  /**
   * What the header comment says (with the experimental note): where the
   * schema came from, the `--fake` command, and the notes about materialized
   * views and `max_locks_per_transaction` when they apply.
   */
  readonly header: HeaderMeta;
}

/**
 * Options of `generateMigration()`.
 */
export interface GenerateOptions {
  /**
   * The language of the migration.
   */
  readonly language: OutputLanguage;

  /**
   * The schema that names are relative to (see
   * {@link EmitContext.defaultSchema}).
   */
  readonly defaultSchema: string;

  /**
   * Fail with `UNSUPPORTED_OBJECTS`, listing every fallback and why, instead
   * of writing a migration that has any.
   *
   * @default false
   */
  readonly strict?: boolean;

  /**
   * The migration name (the file name without its extension).
   */
  readonly migrationName: string;

  /**
   * The command that records the migration as run without running it (see
   * `formatFakeCommand()`).
   */
  readonly fakeCommand: string;

  /**
   * Where the schema came from (the live server's version).
   */
  readonly source: DumpSource;

  /**
   * The server's `max_connections`, to size the `max_locks_per_transaction`
   * note (see `requiredMaxLocksPerTransaction()`).
   *
   * @default 100
   */
  readonly maxConnections?: number;

  /**
   * The server's `max_prepared_transactions`, to size the
   * `max_locks_per_transaction` note.
   *
   * @default 0
   */
  readonly maxPreparedTransactions?: number;
}

/**
 * A migration generated by `generateMigration()`.
 */
export interface GeneratedMigration {
  /**
   * The content of the migration file, ending with a single `\n`.
   */
  readonly content: string;

  /**
   * The objects created with raw SQL, in the order of the migration.
   */
  readonly fallbacks: ReadonlyArray<Fallback>;

  /**
   * How many objects of each kind the migration creates, counted like a
   * dump's (see `DumpStats`): tables (partitions included), indexes,
   * primary key / unique / exclusion constraints, sequences (identity and
   * serial ones included), views and materialized views.
   */
  readonly stats: DumpStats;
}
