import type { Fallback } from '../codegen/fallback';
import type { CatalogConnection } from '../introspect/types';
import { resolveCatalogOptions } from './core/plan';
import { generateCatalogBaseline } from './io/catalogBaseline';
import type { DumpSource } from './source';

// The entry `node-pg-migrate/baseline/catalogs`: what `baseline()` does with
// `format` `'ts'` or `'js'`, without Node.js. It must only import modules that
// run anywhere (no `node:*` module, no pg, no `process` or `Buffer`), so that
// a browser can use it, e.g. against PGlite. Its exported types must not
// reach pg's either.

export { BaselineError } from './errors';
export type { BaselineErrorCode } from './errors';
export type { Fallback } from '../codegen/fallback';
export type { DumpSource } from './source';

/**
 * A connection to the database whose catalogs to read: anything with a
 * node-postgres-like `query()`, such as a `pg` `Client` or a PGlite instance.
 *
 * Every query must run in the same session, so a single connection rather
 * than a pool, and the session must not be in a transaction:
 * `generateBaselineFromCatalogs()` reads in transactions of its own, which it
 * rolls back. It never closes the connection.
 */
export interface CatalogClient {
  /**
   * Runs one SQL statement.
   *
   * @param text The statement, with `$1`, `$2`, … placeholders.
   * @param values The values of the placeholders.
   * @returns The rows, one object per row keyed by column name, with the
   * values parsed the way node-postgres parses them (e.g. booleans as
   * booleans and arrays as arrays).
   */
  query(
    text: string,
    values?: unknown[]
  ): Promise<{ readonly rows: unknown[] }>;
}

/**
 * Options of `generateBaselineFromCatalogs()`: the options of `baseline()`
 * that decide what a TypeScript or JavaScript baseline says, with the same
 * names and defaults, plus the migration name that `baseline()` would pick.
 */
export interface CatalogBaselineOptions {
  /**
   * The language of the migration: TypeScript or JavaScript `pgm` calls, like
   * `baseline()`'s `format` `'ts'` and `'js'`.
   *
   * @default 'ts'
   */
  readonly format?: 'ts' | 'js';

  /**
   * The migration name: the file name without its extension, as the
   * migrations table records it, e.g. `1700000000000_baseline` (what
   * `BaselineResult.migrationName` is). The header of the migration and its
   * `--fake` command name it.
   */
  readonly migrationName: string;

  /**
   * The migrations directory, as the user gives it to node-pg-migrate. Only
   * the `--fake` command names it (`-m <dir>` when it is not `migrations`):
   * nothing is written.
   *
   * @default 'migrations'
   */
  readonly dir?: string;

  /**
   * The table storing which migrations have been run.
   *
   * @default 'pgmigrations'
   */
  readonly migrationsTable?: string;

  /**
   * The schema storing the table which migrations have been run.
   *
   * (defaults to the first schema of `schema`, else `'public'`)
   */
  readonly migrationsSchema?: string;

  /**
   * The schema(s) on which migrations are run, like `baseline()`'s `schema`:
   * names in the migration are relative to the first one.
   *
   * @default 'public'
   */
  readonly schema?: string | string[];

  /**
   * Only read these schemas, like `baseline()`'s `includeSchemas`:
   * extensions are kept whatever their schema, and casts, which belong to no
   * schema, are left out.
   */
  readonly includeSchemas?: ReadonlyArray<string>;

  /**
   * Leave these schemas out of what is read.
   */
  readonly excludeSchemas?: ReadonlyArray<string>;

  /**
   * Fail with `UNSUPPORTED_OBJECTS`, listing every object that would need raw
   * SQL and why, instead of generating a migration with fallbacks.
   *
   * @default false
   */
  readonly strict?: boolean;

  /**
   * Whether the migrations run with `decamelize` (see
   * `RunnerOption.decamelize`). Then a database whose identifiers decamelize
   * would rename is refused with `INVALID_OPTIONS`.
   *
   * @default false
   */
  readonly decamelize?: boolean;
}

/**
 * The baseline migration generated by `generateBaselineFromCatalogs()`: what
 * `baseline()` returns for a TypeScript or JavaScript baseline, without the
 * file path, and with the content of the file.
 */
export interface CatalogBaselineResult {
  /**
   * The migration, exactly as `baseline()` writes it to its file for the
   * same database and options.
   */
  readonly content: string;

  /**
   * The migration name, as given (`CatalogBaselineOptions.migrationName`).
   */
  readonly migrationName: string;

  /**
   * The command that records the migration as run without running it, for
   * databases that already have this schema, e.g.
   * `node-pg-migrate up 1700000000000_baseline --fake`.
   */
  readonly fakeCommand: string;

  /**
   * About how many relations the migration creates in its transaction.
   */
  readonly relations: number;

  /**
   * The `max_locks_per_transaction` a blank database needs to run the
   * migration. Only set when it is more than the default of 64.
   */
  readonly requiredMaxLocksPerTransaction?: number;

  /**
   * What the user should know about the migration. Nothing is logged: the
   * caller shows them.
   */
  readonly warnings: ReadonlyArray<string>;

  /**
   * Where the schema came from: the version of the server.
   */
  readonly source: DumpSource;

  /**
   * The objects the migration creates with raw SQL (`pgm.sql(…)`), in the
   * order of the migration; empty when there are none.
   */
  readonly fallbacks: ReadonlyArray<Fallback>;
}

/**
 * Reads the catalogs through a caller's client the way `baseline()` reads
 * them through a `DBConnection`, except that nothing is logged: statements
 * and queries are passed to its `query()`, the values of a query's
 * placeholders only when it has some.
 *
 * @param client The caller's client.
 */
function catalogConnection(client: CatalogClient): CatalogConnection {
  return {
    query: (text) => client.query(text),
    select: async (query) => {
      const { rows } =
        typeof query === 'string'
          ? await client.query(query)
          : await client.query(query.text, query.values);

      return rows;
    },
  };
}

/**
 * Generates the TypeScript or JavaScript baseline migration of a database
 * from its catalogs, through any client with a node-postgres-like `query()`:
 * the same migration that `baseline()` writes with `format` `'ts'` or `'js'`
 * for that database and the same options, byte for byte, and what
 * `baseline()` returns about it. It runs without Node.js (e.g. in a browser
 * against PGlite), writes no file and logs nothing.
 *
 * Like `baseline()`, it checks the options, the server and the migration
 * history first, and throws a `BaselineError` with the same code as
 * `baseline()` when the database cannot get a baseline: `INVALID_OPTIONS`
 * for options that `baseline()` refuses too (a `format` other than `'ts'` or
 * `'js'`, an empty `migrationName`, `dir`, `migrationsTable` or
 * `migrationsSchema`, or a migration name with spaces or slashes),
 * `includeSchemas` that name no schema or identifiers that `decamelize`
 * would rename, `UNSUPPORTED_SERVER` for a server that is not PostgreSQL,
 * `HISTORY_EXISTS` when the migrations table records migrations,
 * `INVALID_MIGRATIONS_TABLE` when a relation with its name is not a table,
 * and `UNSUPPORTED_OBJECTS` for objects that the migration cannot create
 * (with `strict`, the ones that need raw SQL).
 *
 * @param client The database (see {@link CatalogClient}). It is left open,
 * outside any transaction.
 * @param options The migration name and the options of `baseline()` that
 * decide what the migration says.
 * @returns The migration, and what the user should know about it.
 */
export async function generateBaselineFromCatalogs(
  client: CatalogClient,
  options: CatalogBaselineOptions
): Promise<CatalogBaselineResult> {
  const { settings, catalog } = resolveCatalogOptions(options);

  return generateCatalogBaseline(
    catalogConnection(client),
    settings,
    catalog,
    options.migrationName
  );
}
