import { describe, expect, it } from 'vitest';
import { renderHeader } from '../../../src/baseline/core/header';
import type { HeaderMeta } from '../../../src/baseline/types';
import { getActions } from '../../../src/sqlMigration';

const META: HeaderMeta = {
  migrationName: '1700000000000_baseline',
  fakeCommand: 'node-pg-migrate up 1700000000000_baseline --fake',
  source: { serverVersion: '18.6', pgDumpVersion: '18.6' },
  materializedViews: 0,
  relations: 42,
};

describe('renderHeader', () => {
  it('keeps every line a comment when the file name or the command has line breaks', () => {
    const header = renderHeader({
      ...META,
      fakeCommand:
        "node-pg-migrate up 1700000000000_baseline --fake -m 'a\nDROP TABLE users; --'",
      source: { file: 'dump\r\n-- Down Migration\n.sql' },
    });
    const lines = header.split('\n');

    expect(lines.slice(0, -2).filter((line) => !line.startsWith('--'))).toEqual(
      []
    );
    expect(header).not.toContain('\r');
    expect(getActions(`${header}SELECT 1;\n`).down).toBe(false);
  });

  it('leaves out empty versions and file names', () => {
    expect(
      renderHeader({
        ...META,
        source: { file: '', serverVersion: '', pgDumpVersion: '17.2' },
      }).split('\n')[1]
    ).toBe(
      '-- Baseline generated by `node-pg-migrate baseline` from PostgreSQL (pg_dump 17.2).'
    );
  });

  it.each([undefined, 0, 64])(
    'has no note about locks when blank databases need %j',
    (requiredMaxLocksPerTransaction) => {
      expect(
        renderHeader({
          ...META,
          relations: 99_999,
          requiredMaxLocksPerTransaction,
        })
      ).not.toContain('max_locks_per_transaction');
    }
  );

  it('formats large relation counts with thousands separators', () => {
    expect(
      renderHeader({
        ...META,
        relations: 1_234_567,
        requiredMaxLocksPerTransaction: 15_488,
      })
    ).toContain(
      '-- It creates about 1,234,567 relations in one transaction, so blank databases need\n--   max_locks_per_transaction = 15488 or more (the default is 64).\n'
    );
  });
});
