import { afterEach, describe, expect, it, vi } from 'vitest';
import { renderHeader } from '../../../src/baseline/core/header';
import type { DumpSource, HeaderMeta } from '../../../src/baseline/types';
import type { MigrationBuilder } from '../../../src/migrationBuilder';
import {
  createMigrationCommentRegex,
  getActions,
} from '../../../src/sqlMigration';

/**
 * A header without the optional notes.
 */
const META: HeaderMeta = {
  migrationName: '1700000000000_baseline',
  fakeCommand: 'node-pg-migrate up 1700000000000_baseline --fake',
  source: { serverVersion: '18.6', pgDumpVersion: '18.6' },
  materializedViews: 0,
  relations: 42,
};

/**
 * The second line of a header: where the schema came from.
 */
function sourceLineOf(source: DumpSource): string {
  return renderHeader({ ...META, source }).split('\n')[1] ?? '';
}

/**
 * Leftovers of versions that were left out: `undefined`, empty parentheses,
 * dangling commas and double spaces.
 */
const LEFTOVERS =
  /undefined|null|\(\s*\)|\(\s*,|,\s*\)|,\s*,|,\s*\.|\s\.$|\s,| {2}/;

describe('renderHeader', () => {
  afterEach(() => {
    vi.useRealTimers();
  });

  it('renders the up marker, the source and how to record or run the migration', () => {
    expect(renderHeader(META)).toBe(
      [
        '-- Up Migration',
        '-- Baseline generated by `node-pg-migrate baseline` from PostgreSQL 18.6 (pg_dump 18.6).',
        '-- On databases that already have this schema, record it without running it:',
        '--   node-pg-migrate up 1700000000000_baseline --fake',
        '-- Blank databases run it with a normal `node-pg-migrate up`.',
        '',
        '',
      ].join('\n')
    );
  });

  it('names the dump file and both versions of a dump read from a file', () => {
    expect(
      sourceLineOf({
        file: 'schema.sql',
        serverVersion: '16.4',
        pgDumpVersion: '16.4',
      })
    ).toBe(
      '-- Baseline generated by `node-pg-migrate baseline` from schema.sql (PostgreSQL 16.4, pg_dump 16.4).'
    );
  });

  it('names stdin as the file of a dump read from standard input', () => {
    expect(
      sourceLineOf({
        file: 'stdin',
        serverVersion: '18.6',
        pgDumpVersion: '18.6',
      })
    ).toBe(
      '-- Baseline generated by `node-pg-migrate baseline` from stdin (PostgreSQL 18.6, pg_dump 18.6).'
    );
  });

  it.each([
    {
      name: 'a file without versions',
      source: { file: 'schema.sql' },
      mentions: ['from schema.sql'],
    },
    {
      name: 'a file with only the server version',
      source: { file: 'schema.sql', serverVersion: '15.2' },
      mentions: ['schema.sql', 'PostgreSQL 15.2'],
    },
    {
      name: 'a file with only the pg_dump version',
      source: { file: 'schema.sql', pgDumpVersion: '17.1' },
      mentions: ['schema.sql', 'pg_dump 17.1'],
    },
    {
      name: 'a live server without the pg_dump version',
      source: { serverVersion: '18.6' },
      mentions: ['PostgreSQL 18.6'],
    },
    {
      name: 'a live server with only the pg_dump version',
      source: { pgDumpVersion: '18.6' },
      mentions: ['pg_dump 18.6'],
    },
    {
      name: 'nothing known',
      source: {},
      mentions: [],
    },
  ])(
    'leaves the unknown versions of $name out cleanly',
    ({ source, mentions }) => {
      const line = sourceLineOf(source);

      expect(
        line.startsWith('-- Baseline generated by `node-pg-migrate baseline` ')
      ).toBe(true);
      expect(line.endsWith('.')).toBe(true);
      expect(line).not.toMatch(LEFTOVERS);
      expect(mentions.filter((mention) => !line.includes(mention))).toEqual([]);
    }
  );

  it('says to refresh materialized views when there are any', () => {
    const lines = renderHeader({ ...META, materializedViews: 2 }).split('\n');

    expect(lines).toContain(
      '-- Materialized views are created WITH NO DATA: refresh them after the first run.'
    );
    expect(renderHeader(META)).not.toMatch(/materialized|WITH NO DATA/i);
  });

  it('says how many locks blank databases need when more than the default is required', () => {
    const header = renderHeader({
      ...META,
      relations: 40_500,
      requiredMaxLocksPerTransaction: 512,
    });

    expect(header).toMatch(
      /^-- It creates about 40[, ]?500 relations in one transaction, so blank databases need$/m
    );
    expect(header).toMatch(
      /^-- {3}max_locks_per_transaction = 512 or more \(the default is 64\)\.$/m
    );
    expect(renderHeader(META)).not.toContain('max_locks_per_transaction');
  });

  it('puts the notes after the instructions, materialized views first', () => {
    const lines = renderHeader({
      ...META,
      materializedViews: 1,
      relations: 40_500,
      requiredMaxLocksPerTransaction: 512,
    }).split('\n');
    const blank = lines.indexOf(
      '-- Blank databases run it with a normal `node-pg-migrate up`.'
    );
    const refresh = lines.findIndex((line) => line.includes('WITH NO DATA'));
    const locks = lines.findIndex((line) =>
      line.includes('max_locks_per_transaction')
    );

    expect(blank).toBeGreaterThan(0);
    expect(refresh).toBeGreaterThan(blank);
    expect(locks).toBeGreaterThan(refresh);
  });

  it.each([
    { name: 'the minimal header', meta: META },
    {
      name: 'a header with every note',
      meta: {
        ...META,
        materializedViews: 3,
        relations: 99_999,
        requiredMaxLocksPerTransaction: 1280,
      },
    },
    {
      name: 'a header for a migration and directory named like markers',
      meta: {
        ...META,
        migrationName: '1700000000000_up-migration',
        fakeCommand:
          "node-pg-migrate up 1700000000000_up-migration --fake -m 'down migration'",
        source: { file: 'down migration.sql' },
      },
    },
  ])(
    'ends $name with a blank line, has comments only and no marker after the first line',
    ({ meta }) => {
      const header = renderHeader(meta);
      const lines = header.split('\n');

      expect(header).toMatch(/[^\n]\n\n$/);
      expect(
        lines.slice(0, -2).filter((line) => !line.startsWith('--'))
      ).toEqual([]);
      expect(
        lines
          .slice(1)
          .filter(
            (line) =>
              createMigrationCommentRegex('up').test(line) ||
              createMigrationCommentRegex('down').test(line)
          )
      ).toEqual([]);
    }
  );

  it('makes an up migration of the whole file without a down migration', async () => {
    const content = `${renderHeader({
      ...META,
      materializedViews: 1,
      relations: 40_500,
      requiredMaxLocksPerTransaction: 512,
    })}CREATE TABLE public.t (id integer);\n`;
    const { up, down } = getActions(content);
    const pgm = { sql: vi.fn() };

    expect(down).toBe(false);
    if (typeof up !== 'function') {
      throw new TypeError('expected an up migration');
    }

    await up(pgm as unknown as MigrationBuilder);

    expect(pgm.sql).toHaveBeenCalledExactlyOnceWith(content);
  });

  it('renders the same header at any time, without timestamps', () => {
    vi.useFakeTimers({ toFake: ['Date'] });
    vi.setSystemTime(new Date('2031-02-03T04:05:06.789Z'));
    const first = renderHeader(META);
    vi.setSystemTime(new Date('2032-12-24T23:59:59.000Z'));
    const second = renderHeader(META);

    expect(second).toBe(first);
    expect(first).not.toMatch(/2031|2032|\d{2}:\d{2}/);
  });
});
