import type { DumpSource, HeaderMeta } from '../types';
import { DEFAULT_MAX_LOCKS_PER_TRANSACTION } from './locks';

/**
 * Formats counts with thousands separators, the same way everywhere.
 */
const COUNT_FORMAT = new Intl.NumberFormat('en-US');

/**
 * Where the schema came from, e.g. `PostgreSQL 18.6 (pg_dump 18.6)` for a
 * live server or `schema.sql (PostgreSQL 16.4, pg_dump 16.4)` for a dump
 * file. Unknown versions are left out.
 */
function describeSource(source: DumpSource): string {
  const server = source.serverVersion
    ? `PostgreSQL ${source.serverVersion}`
    : undefined;
  const pgDump = source.pgDumpVersion
    ? `pg_dump ${source.pgDumpVersion}`
    : undefined;

  if (source.file) {
    const versions = [server, pgDump].filter((part) => part !== undefined);

    return versions.length > 0
      ? `${source.file} (${versions.join(', ')})`
      : source.file;
  }

  const origin = server ?? 'PostgreSQL';

  return pgDump === undefined ? origin : `${origin} (${pgDump})`;
}

/**
 * The notes about materialized views and `max_locks_per_transaction`, when
 * they apply.
 */
function notes(meta: HeaderMeta): string[] {
  const lines: string[] = [];
  if (meta.materializedViews > 0) {
    lines.push(
      '-- Materialized views are created WITH NO DATA: refresh them after the first run.'
    );
  }

  const locks = meta.requiredMaxLocksPerTransaction;
  if (locks !== undefined && locks > DEFAULT_MAX_LOCKS_PER_TRANSACTION) {
    lines.push(
      `-- It creates about ${COUNT_FORMAT.format(meta.relations)} relations in one transaction, so blank databases need`,
      `--   max_locks_per_transaction = ${String(locks)} or more (the default is ${String(DEFAULT_MAX_LOCKS_PER_TRANSACTION)}).`
    );
  }

  return lines;
}

/**
 * Renders the comment header of a baseline migration: the `-- Up Migration`
 * marker, where the schema came from, how to record the migration on
 * databases that already have this schema, and, when they apply, notes about
 * materialized views and `max_locks_per_transaction`. It ends with a blank
 * line and has no timestamps, so the same input always renders the same
 * header.
 *
 * Every line is a SQL comment: line breaks in the file name or the command
 * become spaces, so they cannot end a comment.
 *
 * @param meta What the header says.
 */
export function renderHeader(meta: HeaderMeta): string {
  const lines = [
    '-- Up Migration',
    `-- Baseline generated by \`node-pg-migrate baseline\` from ${describeSource(meta.source)}.`,
    '-- On databases that already have this schema, record it without running it:',
    `--   ${meta.fakeCommand}`,
    '-- Blank databases run it with a normal `node-pg-migrate up`.',
    ...notes(meta),
  ];

  return `${lines.map((line) => line.replaceAll(/[\n\r]/g, ' ')).join('\n')}\n\n`;
}
