import type { StartedPostgreSqlContainer } from '@testcontainers/postgresql';
import { execFile as processExecFile } from 'node:child_process';
import { mkdtemp, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { promisify } from 'node:util';
import pg from 'pg';
import {
  afterAll,
  afterEach,
  beforeAll,
  beforeEach,
  describe,
  expect,
  it,
} from 'vitest';
import { escapeValue, runner } from '../../src';
import type { MigrationDirection, RunnerOption } from '../../src/runner';
import {
  cleanupDatabase,
  INTEGRATION_TIMEOUT,
  PG_VERSIONS,
  setupPostgresDatabase,
} from './utils';

// `execFile` returns a ChildProcess, as supported by Node's `promisify`.
// oxlint-disable-next-line typescript/strict-void-return
const execFile = promisify(processExecFile);
const cli = resolve('bin/node-pg-migrate.js');
const existingName = '0000_existing';
const quotedName = "0001_user's-table";

describe.each(PG_VERSIONS)(
  'migration names in history (PG %s)',
  { timeout: INTEGRATION_TIMEOUT },
  (version) => {
    let container: StartedPostgreSqlContainer;
    let client: pg.Client;
    let dir: string;

    beforeAll(async () => {
      container = await setupPostgresDatabase(
        `postgres:${version}-alpine`,
        'migration_names'
      );
      client = new pg.Client(container.getConnectionUri());
      await client.connect();
    }, INTEGRATION_TIMEOUT);

    afterAll(async () => {
      if (client) {
        await client.end();
      }
      if (container) {
        await container.stop();
      }
    });

    beforeEach(async () => {
      dir = await mkdtemp(join(tmpdir(), 'pgm-migration-names-'));
    });

    afterEach(async () => {
      try {
        await cleanupDatabase(container);
      } finally {
        await rm(dir, { recursive: true, force: true });
      }
    });

    function migrate(
      direction: MigrationDirection,
      options: Partial<RunnerOption> = {}
    ) {
      return runner({
        databaseUrl: container.getConnectionUri(),
        dir,
        migrationsSchema: 'public',
        migrationsTable: 'pgmigrations',
        direction,
        log: () => {},
        ...options,
      });
    }

    function runCli(args: string[]) {
      return execFile(process.execPath, [cli, ...args, '-m', dir], {
        cwd: dir,
        // Keep inherited PG* settings from overriding the disposable database.
        env: { DATABASE_URL: container.getConnectionUri() },
      });
    }

    async function history() {
      return (
        await client.query<{ name: string }>(
          'SELECT name FROM public.pgmigrations ORDER BY id'
        )
      ).rows.map(({ name }) => name);
    }

    async function tables() {
      return (
        await client.query<{ tablename: string }>(
          "SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename"
        )
      ).rows.map(({ tablename }) => tablename);
    }

    async function seedHistory() {
      await writeFile(
        join(dir, `${existingName}.cjs`),
        "exports.up = (pgm) => pgm.createTable('existing', { id: 'integer' });"
      );
      await migrate('up');
      await client.query('INSERT INTO existing (id) VALUES (42)');
    }

    async function writeMigration(
      name: string,
      { automatic = false, noTransaction = false } = {}
    ) {
      const transaction = noTransaction ? 'pgm.noTransaction();' : '';
      await writeFile(
        join(dir, `${name}.cjs`),
        `exports.up = (pgm) => {
          ${transaction}
          pgm.createTable('created', { id: 'integer' });
        };
        ${
          automatic
            ? ''
            : `exports.down = (pgm) => {
          ${transaction}
          pgm.dropTable('created');
        };`
        }`
      );
    }

    async function expectExistingUnchanged() {
      expect((await client.query('SELECT id FROM existing')).rows).toEqual([
        { id: 42 },
      ]);
      expect(await history()).toEqual([existingName]);
    }

    it('should apply and roll back an apostrophe name generated by the CLI', async () => {
      await runCli([
        'create',
        "user's-table",
        '-j',
        'cjs',
        '--migration-filename-format',
        'index',
      ]);
      expect(await readdir(dir)).toEqual([`${quotedName}.cjs`]);

      await runCli(['up']);
      expect(await history()).toEqual([quotedName]);
      const second = await runCli(['up']);
      expect(second.stdout).toContain('No migrations to run!');
      await runCli(['down']);
      expect(await history()).toEqual([]);
    });

    it.each([
      { name: quotedName, automatic: false },
      { name: quotedName, automatic: true },
      { name: "0001_users''table", automatic: false },
      { name: "0001_' OR '1'='1", automatic: false },
      { name: "0001_'; DELETE FROM pgmigrations; --", automatic: false },
      { name: '0001_tag$pga$', automatic: false },
      { name: '0001_tag$pga', automatic: false },
      { name: '0001_tag$pga$pgb', automatic: false },
    ])(
      'should round-trip $name (inferred down: $automatic)',
      async ({ name, automatic }) => {
        await seedHistory();
        await writeMigration(name, { automatic });

        await migrate('up');
        expect(await history()).toEqual([existingName, name]);
        expect(await tables()).toEqual(['created', 'existing', 'pgmigrations']);
        expect(await migrate('up')).toEqual([]);
        await migrate('down');
        expect(await tables()).toEqual(['existing', 'pgmigrations']);
        await expectExistingUnchanged();
      }
    );

    it.each([quotedName, "0001_' OR '1'='1"])(
      'should delete only the matching pre-existing history row for %s',
      async (name) => {
        await seedHistory();
        await writeMigration(name);
        await client.query('CREATE TABLE created (id integer)');
        await client.query(
          'INSERT INTO pgmigrations (name, run_on) VALUES ($1, NOW())',
          [name]
        );

        await migrate('down');

        expect(await tables()).toEqual(['existing', 'pgmigrations']);
        await expectExistingUnchanged();
      }
    );

    it.each([true, false])(
      'should record nontransactional changes with singleTransaction: %s',
      async (singleTransaction) => {
        await seedHistory();
        await writeMigration(quotedName, { noTransaction: true });

        await migrate('up', { singleTransaction });
        expect(await tables()).toEqual(['created', 'existing', 'pgmigrations']);
        expect(await history()).toEqual([existingName, quotedName]);
        expect(await migrate('up', { singleTransaction })).toEqual([]);
        await migrate('down', { singleTransaction });
        expect(await tables()).toEqual(['existing', 'pgmigrations']);
        await expectExistingUnchanged();
      }
    );

    it('should fake both directions without running migration actions', async () => {
      await seedHistory();
      await writeFile(
        join(dir, `${quotedName}.cjs`),
        `exports.up = () => { throw new Error('up must not run'); };
         exports.down = () => { throw new Error('down must not run'); };`
      );

      await runCli(['up', '--fake']);
      expect(await history()).toEqual([existingName, quotedName]);
      expect(await tables()).toEqual(['existing', 'pgmigrations']);
      await runCli(['down', '--fake']);
      await expectExistingUnchanged();
    });

    it.each([false, true])(
      'should leave a fresh database unchanged on dry up with fake: %s',
      async (fake) => {
        await writeMigration(quotedName);

        const result = await runCli([
          'up',
          '--dry-run',
          ...(fake ? ['--fake'] : []),
        ]);

        expect(result.stdout).toContain("$pga$0001_user's-table$pga$");
        expect(await tables()).toEqual([]);
      }
    );

    it.each([false, true])(
      'should preserve existing data and history on dry down with fake: %s',
      async (fake) => {
        await seedHistory();
        await writeMigration(quotedName);
        await migrate('up');
        await client.query('INSERT INTO created (id) VALUES (7)');
        const before = (
          await client.query('SELECT * FROM pgmigrations ORDER BY id')
        ).rows;

        const result = await runCli([
          'down',
          '--dry-run',
          ...(fake ? ['--fake'] : []),
        ]);

        expect(result.stdout).toContain("$pga$0001_user's-table$pga$");
        expect(
          (await client.query('SELECT * FROM pgmigrations ORDER BY id')).rows
        ).toEqual(before);
        expect((await client.query('SELECT id FROM created')).rows).toEqual([
          { id: 7 },
        ]);
        expect((await client.query('SELECT id FROM existing')).rows).toEqual([
          { id: 42 },
        ]);
      }
    );

    it('should round-trip escaped strings and arrays independently of backslash settings', async () => {
      const values = [String.raw`user\'s`, 'tag$pga', 'tag$pga$pgb'];
      try {
        await client.query('SET standard_conforming_strings = off');
        for (const value of values) {
          const result = await client.query<{ value: string }>(
            `SELECT ${escapeValue(value)}::text AS value`
          );
          expect(result.rows).toEqual([{ value }]);
        }
        const result = await client.query<{ value: string[][] }>(
          `SELECT ${escapeValue([values])}::text[] AS value`
        );
        expect(result.rows).toEqual([{ value: [values] }]);
      } finally {
        await client.query('RESET standard_conforming_strings');
      }
    });
  }
);
