name: Cockroach Test

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [22]
        cockroach_version: [23.2.28, 24.3.23, 25.3.5]
      fail-fast: false
    timeout-minutes: 10

    name: 'Cockroach Test: cockroach-${{ matrix.cockroach_version }}, node-${{ matrix.node_version }}, ubuntu-latest'
    steps:
      - name: Init Cockroach
        env:
          COCKROACHDB_DOCKER_TAG: cockroachdb/cockroach:v${{ matrix.cockroach_version }}
          DATABASE_URL: postgresql://root@localhost:26257/integration_test
        run: |
          docker pull $COCKROACHDB_DOCKER_TAG
          docker run -d --name roach --hostname roach -p 26257:26257 -p 8080:8080 $COCKROACHDB_DOCKER_TAG start-single-node --insecure
          sudo apt update && sudo apt install wait-for-it -y
          wait-for-it -h localhost -p 26257
          docker exec roach bash -c "./cockroach sql --execute=\"CREATE DATABASE integration_test;\" --insecure"

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Integration Test
        run: pnpm run migrate up -m test/cockroach --no-lock && pnpm run migrate down 0 -m test/cockroach --no-lock --timestamps
        env:
          DATABASE_URL: postgresql://root@localhost:26257/integration_test
