name: Coverage Report

on:
  workflow_run:
    workflows: ['Coverage']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest

    permissions:
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Download Artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: coverage-${{ github.event.workflow_run.id }}
          path: coverage

      - name: Download main Artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: coverage-main
          path: coverage-main

      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@d63aa97db4c0319f304f1787689de1ca548365cf # v2.11.1
        with:
          file-coverage-mode: all
          json-summary-compare-path: coverage-main/coverage-summary.json
